name: CI Tests

on: pull_request

env:
  CI: true
  GIT_COMMIT_SHA: ${{ github.sha }}
  GIT_BRANCH: ${{ github.head_ref }}
  CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}

jobs:
  precommit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        # Update this as GitHub changes simulator versions
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 11']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Validate Pre-Commit checks
        run: |
          pip install pre-commit
          pre-commit run --all-files -c .pre-commit-config-ci.yml
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: 3.3.5

      - uses: actions/checkout@v2
      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze Project Source
        run: dart analyze
